### ISSUE TITLE
diffy proxy report show no data, but proxy  process difference normally.

### ISSUE THREAD

**Issue by victordudu1121** [opendiffy/diffy#10]
@puneetkhanduri  
    
I often encounter diffy proxy processing downstream three returns to normal, get raw_diff data is normal, but the report does not display any results, the data obtained by the api layer is {}
I started the multiple Diffy instance on the same host, bound to a different port, and there is no error message.  

![image](https://user-images.githubusercontent.com/44863344/50390189-f7ff2000-076e-11e9-80f1-529582449a08.png)

When I kill all the diffy instances, restarting one diffy instance, then the report will show the right diff result.

on the same host, start multiple diffy instances for service, will it affect each other?

Suffering from the above problems, I often run 10 times, 5-6 reports have no data, I went into diffy / compare and diffy / analysis to println debugging information, as follows:
 
![image](https://user-images.githubusercontent.com/44863344/50390015-7ad2ab80-076c-11e9-81e7-264ec3ef0ee9.png)

Thank you very much for your guidance.

**Comment by puneetkhanduri** [comment]
Hi Victor. How many requests are you sending for each endpoint in your runs? Sending larger volumes of requests usually leads to more robust results with Diffy.

**Comment by victordudu1121** [comment]
> Hi Victor. How many requests are you sending for each endpoint in your runs? Sending larger volumes of requests usually leads to more robust results with Diffy.


@puneetkhanduri  
Sorry.  sorry for the late reply. I send requests 1000-10000 requests.  This happens frequently.  I debug it. Found the  diffy get right response from third downstream. So. What are the possible reasons, and what are the clues for troubleshooting?

**Comment by puneetkhanduri** [comment]
Closing old issues. Please comment if needs to be re-opened.
