### ISSUE TITLE
Diffy won't report results 

### ISSUE THREAD

**Issue by asos-francesca** [opendiffy/diffy#11]
Using docker, wanting to compare my local dev instance with production, running:

```
docker run -d --name diffy-01 \
  -p 8880:8880 -p 8881:8881 -p 8888:8888 \
  diffy/diffy \
    -candidate=localhost:3000 \
    -master.primary=www.myproductionenv.com \
    -master.secondary=www.myproductionenv.com \
    -service.protocol=http \
    -serviceName="Test" \
    -proxy.port=:8880 \
    -admin.port=:8881 \
    -http.port=:8888 \
    -rootUrl=localhost:8888
```

Then: `curl localhost:8880/my/path/to/page`

I get nothing. No results in the diffy comparison window. No errors. No logging. No network problems.

**Comment by puneetkhanduri** [comment]
You can turn logging on from the admin console(localhost:8881/admin) for the DifferenceProxy package to see if there are any networking or payload parsing failures happening. Please share the logs once you have them for further troubleshooting if necessary.

**Comment by IgorPolyakov** [comment]
if you are running `diffy` from the docker container, make sure that the `master`, `secondary` & `candidate` is available for your network (localhost)

helped me `docker run -ti --net=host  \ ...` without port forwarding

**Comment by puneetkhanduri** [comment]
Closing old issues. Please comment if needs to be re-opened.

**Comment by Frietziek** [comment]
Hello, I have the same issue. In fact, the docker image starts ok and when I do the curl, it gives me back the api result correctly, but when I go to the front-end o diffy on localhost:8888, nothing had happen :/...I mean, is empty, there is nothing logged
