### ISSUE TITLE
localhost can change  different ip adrees ？

### ISSUE THREAD

**Issue by willisfeng** [opendiffy/diffy#13]
Can three different versions of servers be deployed on a single machine with this service?
java -jar diffy-server.jar \
-candidate=172.16.3.1:9992 \
-master.primary=172.16.3.2:9990 \
-master.secondary=172.16.3.3:9991 \
-service.protocol=http \
-serviceName=My-Service \
-proxy.port=:8880 \
-admin.port=:8881 \
-http.port=:8888 \
-rootUrl='localhost:8888'

**Comment by puneetkhanduri** [comment]
You can use Diffy to do arbitrary 3-way comparisons between 3 simultaneously running servers. It doesn't matter of all 3 servers are running on the same machine or different ones.

The standard use case is to run the same version on primary and secondary and a different candidate version on the third one. You will get results if you run three different versions on primary, secondary, and candidates. However, the interpretation of these results is completely up to you. The UI will not break but what you see in the Diffy UI may not make a lot of sense.

**Comment by willisfeng** [comment]
If the service and diffy are not on the same machine, return to display 404 pages

**Comment by willisfeng** [comment]
Accessing all three services individually can be displayed

**Comment by willisfeng** [comment]
404
chunked: false
content
body
attributes
children
0
attributes
children
tag: h1
text: HTTP Status 404 - /jjslogin/tologin
1
attributes
noshade: noshade
size: 1
children
tag: hr
text:
2
attributes
children
0
attributes
children
tag: b
text: type
tag: p
text: Status report
3
attributes
children
0
attributes
children
tag: b
text: message
1
attributes
children
tag: u
text: /jjslogin/tologin
tag: p
text:
4
attributes
children
0
attributes
children
tag: b
text: description
1
attributes
children
tag: u
text: The requested resource is not available.

**Comment by puneetkhanduri** [comment]
Can you curl your services from the diffy machine? This could be a network issue.

**Comment by willisfeng** [comment]
---------------------------------------------------
This is the result of the proxy return.172.16.3.78 is the diffy machine

[root@ceshi-dianzhihetong-3-78 ~]# curl -i  172.16.3.78:8880/jjslogin/tologin
HTTP/1.1 200 OK
Content-Length: 0
--------------------------------------------
This is the result of the service return.  Server access is normal，172.16.3.100 is the Server machine

[root@ceshi-dianzhihetong-3-78 ~]# curl -i  172.16.3.100/jjslogin/tologin
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 27 Apr 2019 05:25:09 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Content-Language: en-US
