### ISSUE TITLE
Show headers for differences

### ISSUE THREAD

**Issue by ramunasm** [opendiffy/diffy#14]
Hello,

Is there a way to display headers for the POST request that resulted in differences?

Thank you

**Comment by puneetkhanduri** [comment]
Yes. Add the following flag:
 -allowHttpSideEffects=true
This will enable POST,PUT, DELETE requests to be compared. Header comparison is on by default and can be controlled explicitly using the following flag:
-excludeHttpHeadersComparison=false

**Comment by ramunasm** [comment]
I know how to enable POST support, and that works fine. But when a POST request results in differences, I can't see the headers of the original request, just the response headers.
I'm looking for a way to get the headers of the original request.

**Comment by puneetkhanduri** [comment]
Sorry I misunderstood your request. I have added this feature. Once this change is merged, you should now be able to see everything about the request including headers and query params.

**Comment by puneetkhanduri** [comment]
merged

**Comment by ramunasm** [comment]
Thank you! That was really fast :)
BTW, It would probably also be a good idea to update the docker hub with the latest version
