### ISSUE TITLE
Error setting diffy with HTTPS

### ISSUE THREAD

**Issue by kshitij10496** [opendiffy/diffy#16]
I'm trying to set up `diffy` to test an HTTPS API.
Here is the Docker command I'm running:
```sh
$ docker run --rm -d --name diffy-test \
  -ti -p 8880:8880 -p 8881:8881 -p 8888:8888 -p 123:123 \
  diffy/diffy \
    -candidate='https://<candidate>.com' \
    -master.primary='https://<prod>.com' \
    -master.secondary='https://<prod>.com' \
    -service.protocol=https \
    -serviceName="Beta-Testing" \
    -proxy.port=:8880 \
    -admin.port=:8881 \
    -https.port=:123 \
    -rootUrl=localhost:8888
```

I'm sending traffic on 8880 but there is no diff on the Web UI.
What am I missing here?
What is the correct way to setup diffy with HTTPS?

**Comment by kshitij10496** [comment]
cc @puneetkhanduri 
Any pointers on how to setup `diffy` here?

**Comment by haihn168** [comment]
Try to add https default port on three instances if you use if with specific domain, example: https://<candidate>.com:443

**Comment by puneetkhanduri** [comment]
The format should be as follows:
```
    -candidate='<candidate>.com:443' \
    -master.primary='<prod>.com:443' \
    -master.secondary='<prod>.com:443' \
```
