### ISSUE TITLE
Unable to email report

### ISSUE THREAD

**Issue by kshitij10496** [opendiffy/diffy#17]
I'm trying to export the report via the email extension provided by `diffy`.
After reading all the documentation and most of the code, I could figure out that specifying `notifications.targetEmail` flag would [automate an email from `Diffy <diffy@no-reply.com>`](https://github.com/opendiffy/diffy/blob/9d0f573f891c43754e3cfc5be8507e3aad2d68a5/src/main/scala/ai/diffy/workflow/ReportGenerator.scala#L49)

Here is the docker command being used:
```sh
docker run --rm -d --name diffy-staging-clarisights \
  -ti -p 8880:8880 -p 8881:8881 -p 8888:8888 \
  diffy/diffy \
    -candidate=localhost:9000 \
    -master.primary=localhost:9001 \
    -master.secondary=localhost:9001 \
    -service.protocol=http \
    -serviceName="Production-Test" \
    -proxy.port=:8880 \
    -admin.port=:8881 \
    -http.port=:8888 \
    -rootUrl=localhost:8888 \
    -notifications.targetEmail="kshitij.saraogi@gmail.com" \
    -notifications.delay=10.minutes
```

Assuming that a SMTP service (namshi/smtp image) listening on `localhost:25` accessible by the container. (I'm running both of them in a K8s pod). However, I'm not able the diffy is having issues sending the email. Is there a workaround to exporting data from `diffy`?

**Comment by haihn168** [comment]
I change the configuration of smtp server in the code and it send well with Gmail smtp.
 And you can also use the api to get the report: /api/1/report

**Comment by kshitij10496** [comment]
Hey @haihn168 

Thanks for replying.
Would it possible for you to share a sample of the changes you made to the SMTP server?
I would be very grateful if you help me fix it.

**Comment by haihn168** [comment]
Below is my code for gmail smtp:

`private[this] val props = new Properties
  props.put("mail.smtp.host", "smtp.gmail.com")
  props.put("mail.smtp.auth", "true")
  props.put("mail.smtp.port", "587")
  props.put("mail.smtp.starttls.enable", "true")

  private[this] val session = Session.getDefaultInstance(props,
    new Authenticator() {
      override protected def getPasswordAuthentication = new PasswordAuthentication("$emailhere", "$password")
    }
  )`

**Comment by meeraeldhose** [comment]
@haihn168 @puneetkhanduri I am trying to do the same here. Because i have enabled the 2 factor authentication, I want to check what should be the app name when configuring on google account ?

**Comment by haihn168** [comment]
@meeraeldhose I dropped this project 2 years ago. No idea now.
