### ISSUE TITLE
When the three instances(candidate,primary ,secondary )  are using different protocols,what should we do? 

### ISSUE THREAD

**Issue by yufenyan** [opendiffy/diffy#19]
At present,the protocol has the only parameter.But if the instances  are using different protocols,what should we do? 
    For example,the candidate instance uses HTTP protocol,while  primary and secondary instances use HTTPS protocol.Whatever protocol（HTTP  or HTTPS） I set，it doesn't work.
    Look forward to your reply.

**Comment by puneetkhanduri** [comment]
This is currently not supported in Diffy. All 3 targets - primary, secondary, and candidate need to share the same protocol.
