### ISSUE TITLE
Fetch all the requests being performed on Diffy

### ISSUE THREAD

**Issue by kshitij10496** [opendiffy/diffy#21]
Currently, I'm able to get only those requests which show a genuine difference. 
Is there a way to fetch information about individual requests, irrespective of whether there is a diff or not, possibly using the `/api/1/requests/:id` endpoint? Moreover, how can we get the request ID for every request?

**Comment by puneetkhanduri** [comment]
@kshitij10496 : We can support this use case but would like to understand how this will create value for all users. It might be easier to discuss this over a quick hangout call. Please feel free to ping me at puneet.khanduri@gmail.com.

**Comment by kshitij10496** [comment]
Hey,

I was occupied with some other tasks, so I couldn't get back to you earlier. 
Nonetheless, I'd be happy to schedule a call with you next week. 
I'll reach out to you over mail by tomorrow.
