### ISSUE TITLE
cannot resolve symbol thriftscala

### ISSUE THREAD

**Issue by yufenyan** [opendiffy/diffy#23]
when ran the  Main.scala, I got the error "Error:(8, 17) object thriftscala is not a member of package ai.diffy"  ,and i could not find thriftscala.

![image](https://user-images.githubusercontent.com/43695092/63840546-d5836d80-c9b3-11e9-8b74-e1dc85307f21.png)

![image](https://user-images.githubusercontent.com/43695092/63840482-b5ec4500-c9b3-11e9-80ff-edb04ca9e800.png)

**Comment by puneetkhanduri** [comment]
This is likely a local build issue. Have you tried deleting the build cache for your ide?

**Comment by yufenyan** [comment]
yes，i had tried ,but it did not work.

**Comment by puneetkhanduri** [comment]
You can try running ./sbt compile to recompile the thrift.

Side: If you just want to run Diffy the fastest way is to either download the built jar [here](https://github.com/opendiffy/diffy/releases/latest) or pull the docker image [here](https://hub.docker.com/r/diffy/diffy)

**Comment by puneetkhanduri** [comment]
@yufenyan : Can you confirm if any of the above solutions have unblocked you.

**Comment by yufenyan** [comment]
yes，i have resolve this problem,thank you so much.
