### ISSUE TITLE
Point Multiple IP Addresses to a Single Host Name

### ISSUE THREAD

**Issue by leiguorui** [opendiffy/diffy#26]
How can I set up 3 IP to a same HOSTNAME?

For example :

    -candidate='test.domain.com' \
    -master.primary='test.domain.com' \
    -master.secondary='test.domain.com' \

The real candidate ip is 192.168.244.128, the master.primary ip is 192.168.244.129, the master.secondary ip is 192.168.244.120.

**Comment by puneetkhanduri** [comment]
You need to use the ```host:port``` format agnostic of the domain name:

```
-candidate='192.168.244.128:80' \
-master.primary='192.168.244.129:80' \
-master.secondary='192.168.244.120:80' \
```
