### ISSUE TITLE
Admin page broken

### ISSUE THREAD

**Issue by Israphel** [opendiffy/diffy#27]
Hi there, I just switched from the old diffy to this one, with the same config. I see the requests coming and everything is green, but the admin page is broken, I don't see the graphics and I got warnings about linter:

<img width="1649" alt="Screen Shot 2019-10-02 at 18 00 21" src="https://user-images.githubusercontent.com/720191/66085338-497edb80-e547-11e9-8d98-e4614baf2b91.png">

**Comment by puneetkhanduri** [comment]
We've upgraded to the latest version of finagle (the admin page is powered by Finagle - Diffy uses finagle as a library). This might require loading additional Guice modules in the Diffy server to get this to work again. You are welcome to take a crack. I can also take a look when I have some bandwidth but might not be able to for a while.

**Comment by Israphel** [comment]
Ok, what should I do? install some extra packages?

**Comment by mmikelkevicius0727** [comment]
Hi, I have the same issue, how to solve it?

**Comment by codemak2r** [comment]
the same problem to me.

**Comment by lyling** [comment]
> Hi there, I just switched from the old diffy to this one, with the same config. I see the requests coming and everything is green, but the admin page is broken, I don't see the graphics and I got warnings about linter:
> 
> <img alt="Screen Shot 2019-10-02 at 18 00 21" width="1649" src="https://user-images.githubusercontent.com/720191/66085338-497edb80-e547-11e9-8d98-e4614baf2b91.png">

how to access this pag? i tried :8888/admin, but it is empty page. i start from jar
