### ISSUE TITLE
Return responses from candidate or master to client

### ISSUE THREAD

**Issue by msacchiPPRO** [opendiffy/diffy#28]
Will this feature merged into `twitter/diffy` ever be ported into opendiffy/diffy? 

https://github.com/twitter/diffy/pull/48

I understand that it goes against the project philosophy, but it helps a lot when testing low traffic systems for which we allow side effects (eg. POST requests)

**Comment by adrianlzt** [comment]
Fork with that option (``-responseMode=primary``): https://github.com/hemanth-s-a/diffy

**Comment by puneetkhanduri** [comment]
This issue has been resolved via the introduction of a -responseMode flag. Please see latest [QUICKSTART](https://github.com/opendiffy/diffy/blob/master/QUICKSTART.md)
