### ISSUE TITLE
How to export data from the server

### ISSUE THREAD

**Issue by puneetkhanduri** [opendiffy/diffy#3]
From: https://github.com/twitter/diffy/issues/76
@pedromss: Mind if we move the conversation here.

**Comment by puneetkhanduri** [comment]
@pedromss: Both your suggestions sound good. If you have a working implementation then contributions are always welcome.

**Comment by pedromss** [comment]
I'm working on it.

Don't mind we move the conversation here, but am wondering why?

Should I open PRs for this repo or for twitter/diffy ?

**Comment by puneetkhanduri** [comment]
I would suggest opening a PR for this repo as the fork has diverged significantly and going forward this will the only repo we actively maintain.

**Comment by puneetkhanduri** [comment]
@pedromss Sorry to leave you in the cold. I was away due to a personal issue. Let me know if you still need help.

**Comment by puneetkhanduri** [comment]
Closing old issues. Please comment if needs to be re-opened.
