### ISSUE TITLE
Diffy doesn't work well with reverse proxy

### ISSUE THREAD

**Issue by ethpran** [opendiffy/diffy#30]
I am trying to run diffy against webservers that sit behind a Traefik reverse proxy. It seems like Finarta resolves the hosts of the servers [on startup](https://github.com/twitter/finatra/blob/5676d0387353c6e30a2bc3b4d13f1c2a42e33e69/inject/inject-server/src/main/scala/com/twitter/inject/server/TwitterServer.scala#L124), but what is being resolved is the proxy server and not the downstream servers I am trying to test with Diffy. Is it possible to configure the Diffy proxy somehow to point to the downstream servers of the reverse proxy?

I'm not really a Scala expert, but if I am understanding this correctly and this can be fixed, I'd be happy to do so with some guidance.

**Comment by puneetkhanduri** [comment]
The name resolution is internal to finagle and we can't do much here without moving away from finagle. I might suggest filing a ticket with the finagle project and linking this issue.

I have also pinged the finagle team on Gitter to check if there is a workaround. Let's see what comes back.

**Comment by ethpran** [comment]
Sounds good. Let me know if you need more details to reproduce. the reverse proxy I'm using is [Traefik 1.7.12](https://github.com/containous/traefik/releases/tag/v1.7.12)

**Comment by puneetkhanduri** [comment]
Sure. If you are urgently blocked, you may want to try [Isotope](https://forms.gle/YP8ibNEUr7s8hnQRA).

**Comment by ethpran** [comment]
thanks. ill consider that. for now i have a way of running my application locally not behind the proxy so i'm good, but in the longrun, it would be cool to be able to run it with the proxy

**Comment by puneetkhanduri** [comment]
So our friends from finagle got back to us and suggested a way. We've made the change and merged it. Please try the latest docker build and confirm if this resolves the issue.

**Comment by ethpran** [comment]
@puneetkhanduri i pulled the latest build and it looks like what you did works! i see my requests propagating to the downstream servers. thanks a lot for the prompt assistance and fix!

**Comment by puneetkhanduri** [comment]
Glad it worked. Cheers!
