### ISSUE TITLE
Optionally ignore case of header names

### ISSUE THREAD

**Issue by mroach** [opendiffy/diffy#31]
According to [RFC-2616], HTTP header names are case-insensitive. Diffy should then by default and/or controlled via an option, make case-insensitive comparisons of header names.

This problem showed up for us doing a comparison of a Phoenix app that replaces a Rails app. Phoenix by default returns header names in all lower-case whereas Rails uses title-case.

[RFC-2616]: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by puneetkhanduri** [comment]
Done and merged. Should also land in dockerhub shortly.
