### ISSUE TITLE
How to use it in thrift protocol basic service upgrade

### ISSUE THREAD

**Issue by paulusDong** [opendiffy/diffy#33]
I have some base service use thrift protocol , like hiveserver2。I want to test when basic service upgrade,  is there any problem with my program。

I run diffy with
`java -jar diffy-server.jar  -candidate=192.168.1.2:10000  -master.primary=192.168.1.3:10000  -master.secondary=192.168.1.4:10000  -service.protocol=thrift -thrift.jar='/opt/hbase/lib/hbase-thrift-1.4.10.jar'  -serviceName=Fancy-Service  -proxy.port=:8880  -admin.port=:8881 -http.port=:8888  -rootUrl="localhost:8888" -summary.email="info@diffy.ai" -summary.delay="5" -allowHttpSideEffects=true -thrift.serviceClass=test-service -enableThriftMux=true`

but get a error:
1) Error in custom provider, ai.diffy.lifter.ThriftLifter$InvalidServiceException: Invalid service:

Maybe there's something wrong with the thrift.jar and thrift.serviceClass configuration, but I don't know how to fix it

Really appreciate your time here

**Comment by puneetkhanduri** [comment]
Looks like your thrift jar doesn't contain the thrift definition for your service class. You have to use a class that exists in the jar you are passing.
