### ISSUE TITLE
What is the right way to scale Diffy?

### ISSUE THREAD

**Issue by simiczhang** [opendiffy/diffy#37]
If there would be millions of requests to Diffy proxy, how to scale Diffy ?

Is it possible to start multiple Diffy servers by using same http.port so all requests could be load balanced but the result is still aggregated (not sure if the volume of the result would blow out service behind http.port as well) ?

**Comment by puneetkhanduri** [comment]
Nope. That won't work. Diffy is not designed to be clustered or federated. We had to build [Isotope](https://isotope.sn126.com) from scratch to acheive the scalability you are looking for.

**Comment by simiczhang** [comment]
Ok, got it.
