### ISSUE TITLE
Is there an ability to pass different requestHeader/Cookie to primary, secondary and candidate

### ISSUE THREAD

**Issue by kramrit** [opendiffy/diffy#4]
Hi,

I liked the diff idea.  But got blocked at very beginning because I am not sure how we can pass different requestHeader/Cookies to primary, secondary and candidate deployment?

Note: For real testing, there is need to pass different secureToken to each deployment.

**Comment by puneetkhanduri** [comment]
@kramrit That has definitely been a limitation. The historical reason is that Diffy's primary focus so far has been testing microservices within a service-oriented-architecture where auth termination typically happens on edge services (that serve as reverse proxy) and all other services trust each other.

We have something completely new in the works that addresses this and many other fundamental issues with Diffy. Stay tuned for an announcement soon.

In the meanwhile, contributions are always welcome.

**Comment by kramrit** [comment]
Hi @puneetkhanduri,

Following up on your previous comment where you have mentioned - _"We have something completely new in the works that address this and many other fundamental issues with Diffy. Stay tuned for an announcement soon."_

Would it be possible to provide more info on the announcement and ETA?

Thanks,
Amrit

**Comment by puneetkhanduri** [comment]
[https://twitter.com/pzdk/status/1045632806691295235](Here)'s the announcement!

**Comment by kramrit** [comment]
Hi Puneet,

How I can try the beta version of isotope project? Please note that I had registered for beta access but I didn't get a response.

**Comment by itayB** [comment]
Hi @puneetkhanduri ,

Can you please give me access as well,
We really need such tool with headers customization capabilities.

Thanks!

**Comment by flouthoc** [comment]
It would be great if you could add me to the access list. :+1:  to the feature request

**Comment by kramrit** [comment]
Hi @puneetkhanduri ,

Is there plan to maintain the GitHub open-source diffy project? Can we have this feature merged there?

**Comment by puneetkhanduri** [comment]
We do plan on maintaining Diffy but we are not investing in adding new features at this point. We are happy to review and merge pull requests from users for new features. Unfortunately, Isotope has no code in common with Diffy so there is no way for us to copy features over without having to rewrite them from scratch.
