### ISSUE TITLE
Analysis on diffy results ?

### ISSUE THREAD

**Issue by sandeepanbaidya** [opendiffy/diffy#41]
Currently, I see only Primitive Difference being flagged. Is there a feature which can:
1. detect other differences like ordering changes in a list?
2. show aggregated view of results where we get % of the difference for some fields(keys). 
3. show metrics for some selected fields.
4. record the request patterns.

Also, is there an article where I can read about how it works internally? Does it provide any other API which can be used for maybe storing the diffy results.

**Comment by bingtianbaihua** [comment]
good point
