### ISSUE TITLE
Add some way to make N requests to the servers at start, based on a file

### ISSUE THREAD

**Issue by Frietziek** [opendiffy/diffy#49]
Hello! I'm looking at this tool right know for using it. 

I think it would be awesome and pretty useful if you can have some way of making a set of requests to test your api. I mean, if I understand correctly, supposing you want to make N requests, based in a file with a pool of good data as query params to test the api well...Well, you will have to make a script with a for loop doing a curl for example, based on a file...Or using something like postman for the same...But if you add a param for example when you initialize diffy, and do this for loop in diffy, making the requests, then diffy would be 100% auto-sufficient for this kind of typical tests.

**Comment by bingtianbaihua** [comment]
1
