### ISSUE TITLE
External link to diffyproject.appspot.com within the project

### ISSUE THREAD

**Issue by w495** [opendiffy/diffy#54]
https://github.com/opendiffy/diffy/blob/caf1c4b487a307f1557a3992f4fbfcbff718ae31/src/main/scala/ai/diffy/util/DiffyProject.scala#L17

External link within project. 

We don't understand how to run tests inside internal closed networks without Internet Access. What for do you use this link?

**Comment by kekekekule** [comment]
And after all, @puneetkhanduri, why is localhost:7000 used in case of dev environment?

**Comment by codemak2r** [comment]
The same confusion. Does anyone maintain this repo?  this tool is pretty famous in testerhome. but it doesn't easy to use.

**Comment by puneetkhanduri** [comment]
References to appspot will be removed in the next major release. Thanks for your patience.
