### ISSUE TITLE
Setup DIFFY on wondows machine

### ISSUE THREAD

**Issue by shyju-cv** [opendiffy/diffy#6]
Hi Punith,
I wanted to use DIFFY in testing my RESTful Service, could you please let me know how can I setup DIFFY on wondows machine. I could not find any useful link from internet.

Regards
Shyju

**Comment by puneetkhanduri** [comment]
I tried looking into this but, unfortunately, haven't been able to arrange access to a windows machine so far. Will ask my dad if I can borrow his windows laptop in a couple of days and get back to you.

**Comment by shyju-cv** [comment]
Thanks for the update, waiting for your reply.

Regards
Shyju

**Comment by puneetkhanduri** [comment]
Sorry was never able to get a hold of a windows machine.
Closing old issues. Please comment if needs to be re-opened.
