### ISSUE TITLE
flag "excludeHttpHeadersComparison＝false": flag undefined

### ISSUE THREAD

**Issue by river891105** [opendiffy/diffy#61]
hello，
  i have cloned the code and success generate the diffy-server.jar， when i run by java -jar , flag "excludeHttpHeadersComparison"  occured an error,  flag undefined, how can i reslove this error ?
  
java -jar diffy-server.jar \
    -candidate=xxxx \
    -master.primary=xxxx \
    -master.secondary=xxxx \
    -service.protocol=https \
    -serviceName=Test-Service \
    -proxy.port=:8880 \
    -admin.port=:8881 \
    -http.port=:8889 \
    -rootUrl="localhost:8889" \
    -allowHttpSideEffects=true \
    -responseMode=primary \
    -excludeHttpHeadersComparison＝false

<img width="1030" alt="截屏2021-08-21 下午5 18 32" src="https://user-images.githubusercontent.com/21053797/130317237-a5bfa727-f99c-4d43-af4e-948161d8b018.png">

**Comment by puneetkhanduri** [comment]
I am unable to reproduce the issue on my end. It could be a subtle build issue with the specific jdk/jre on your end. Not sure.

One option you have is to sidestep the problem is to ignore the flag in your java command because the default value for that flag is already false.

**Comment by river891105** [comment]
Thank you for the replay, without the "excludeHttpHeadersComparison",  I can start the service correctly
the default value for that flag is false is great ,thank you
