### ISSUE TITLE
Integration with azure function

### ISSUE THREAD

**Issue by meeraeldhose** [opendiffy/diffy#65]
This is a question. Has there been an attempt to integrate opendiffy with azure function. I am in the process of it and have some questions on it

**Comment by puneetkhanduri** [comment]
@meeraeldhose Please share more context on the nature of integration you have in mind. Azure functions run chunks of code. Are you talking about an azure function sending requests to Diffy or are you trying to embed Diffy like functionality into inside an Azure Function. It it is the latter what target language do you have in mind?
