### ISSUE TITLE
Docker run not working

### ISSUE THREAD

**Issue by achoukou** [opendiffy/diffy#67]
I tried to use the example running on docker, but the diffy proxy is not reachable, the other endpoints are working correctly.

Any idea what might cause the issue?

**Comment by puneetkhanduri** [comment]
@achoukou : Please pull the latest docker image and try with the modified command line arguments demonstrated [here](https://github.com/opendiffy/diffy/blob/master/QUICKSTART.md#using-diffy-with-docker). Kindly share the server logs if the issue persists.

**Comment by puneetkhanduri** [comment]
Please feel free to reopen this issue if you are still facing problems.
