### ISSUE TITLE
the Scrooge which diffy use can not parse apache offical thrift which can by parse apache thrift 0.9.2 normally

### ISSUE THREAD

**Issue by victordudu1121** [opendiffy/diffy#7]
@puneetkhanduri  
I try to use diffy with thrift protocol. but the Scrooge which diffy use can not parse apache offical thrift which can parse by apache thrift 0.9.2 normally.

the thrift idl define like this:
include "common.thrift"
struct Demo {
common.DataType datatype = DataType.JSON
}

when  I run diffy. it raise errors like these:

Caused by: com.twitter.scrooge.frontend.FileParseException: Exception parsing: aweme.thrift
Caused by: com.twitter.scrooge.frontend.TypeNotFoundException: DataType
<undefined position>

@puneetkhanduri  can you help me?  thank you very much.

btw:  another problem  when parse thrift file by scrooge like this.  can we resolve the  limitation of the Scrooge library we use to parse the thrift into AST ? 
The offical apache thrift support it.  
![image](https://user-images.githubusercontent.com/44863344/48239991-105beb00-e40c-11e8-8cf2-aa07549a4ae0.png)

**Comment by puneetkhanduri** [comment]
@victordudu1121 : I don't mean to throw a hot potato but this seems like a Scrooge-specific issue or feature request might be better addressed by the Scrooge team - https://github.com/twitter/scrooge

I can also take a look if you can share your thrift file and it's dependencies to replicate the bug on my end.
