### ISSUE TITLE
A question: What algorithm diffy uses to compare diffs?

### ISSUE THREAD

**Issue by harsh8398** [opendiffy/diffy#70]
I am working on a project that requires diffy so I've been playing around with the diffy for sometime and I had this question that does diffy use some known algorithm to report noise? I tried to look at the code [here](https://github.com/opendiffy/diffy/blob/master/src/main/scala/ai/diffy/compare/Difference.scala), and it seems to be a custom logic that checks for types, length and sequence for comparison.

Thanks in advance!

**Comment by puneetkhanduri** [comment]
Thanks for your interest in Diffy. The difference logic implemented in Diffy is custom (no known algorithm was used for its implementation). Would love to understand any specific objectives you have in mind and help in any way we can.
