### ISSUE TITLE
No diff details shown

### ISSUE THREAD

**Issue by SebastianSolidwork** [opendiffy/diffy#71]
Version: Jar from 19.11.8.00

When I click on "MissingFields" no details are show.

- content of the Response: {"endpoint":"ourEndpoint","path":"result.200.MissingField","requests":[]}
- The console contains an error:
```
diff.js:386 Uncaught TypeError: Cannot read property 'differences' of undefined
    at k.$scope.traverseFields (diff.js:386)
    at Object.<anonymous> (diff.js:440)
    at Object.success (diff.js:111)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

![image](https://user-images.githubusercontent.com/22794134/195375373-00df9e10-51dc-41ad-bc64-e23618485a8e.png)

**Comment by SebastianSolidwork** [comment]
For other reasons I'm currently not able to run the newest state from the repository.
mvn package works, but the execution fails.

**Comment by SebastianSolidwork** [comment]
I will change my user name and repost

**Comment by puneetkhanduri** [comment]
@SebastianSolidwork These jars are outdated and from an old version of the codebase and are no longer supported. Can you use the [docker image](https://github.com/opendiffy/diffy/blob/master/QUICKSTART.md#using-diffy-with-docker) instead?

**Comment by SebastianSolidwork** [comment]
Thanks for the new jar, I can run the app with them.
So far I'm not familiar with Docker. Some more thing I have to dig in …
(I suggest you to keep updating the jars. Docker is another layer of complexity and therefor for same a hindrance)

I'm observing other issues which I have to dig in until I give here further feedback.

**Comment by SebastianSolidwork** [comment]
It works with Version 22
