### ISSUE TITLE
Authorization from header not shared

### ISSUE THREAD

**Issue by SebastianSolidwork** [opendiffy/diffy#72]
I need to do a Basic authorization to access the APIs, but all calls fail with Unauthorized.
I have it at the header of the call of the proxy, but its not shared when Diffy calls the 3 instances. I see that in Wireshark.
I tried the newest Jar 22.10.13.00 as well as the docker image.
![image](https://user-images.githubusercontent.com/22794134/195631775-47f215f0-132a-473f-b9d2-5a5ca94343a4.png)

**Comment by SebastianSolidwork** [comment]
Sent to the proxy from me:
![image](https://user-images.githubusercontent.com/22794134/195645996-4e07b752-fa65-487a-9299-eee482a51a66.png)

Sent from the proxy to all 3 servers:
![image](https://user-images.githubusercontent.com/22794134/195646340-56dc7e7f-e764-4f17-a601-755d103c8071.png)

**Comment by puneetkhanduri** [comment]
Thanks. Found the issue. Stay tuned for a fix.

**Comment by puneetkhanduri** [comment]
The [latest release](https://github.com/opendiffy/diffy/releases/tag/22.10.13.01) fixes the problem. Please confirm this works for you. We will be updating our docker image shortly.

**Comment by SebastianSolidwork** [comment]
It works! Thanks

**Comment by puneetkhanduri** [comment]
Awesome!
