### ISSUE TITLE
Missing reset button

### ISSUE THREAD

**Issue by SebastianSolidwork** [opendiffy/diffy#73]
I miss the reset button in the new UI.

**Comment by puneetkhanduri** [comment]
Your love for the reset button is much appreciated. Sorry we had to drop the reset button in the new UI. We will try to add this back in the next release.

**Comment by SebastianSolidwork** [comment]
Another improvement idea: give me an optional date input field, just entries older than this are dropped. (Or maybe also as range?)

**Comment by puneetkhanduri** [comment]
This has been merged in master and is available in the [latest release](https://github.com/opendiffy/diffy/releases/tag/22.10.29.00). Here you go :
<img width="1435" alt="Screen Shot 2022-10-29 at 10 06 21 AM" src="https://user-images.githubusercontent.com/1631032/198814327-ca848f7b-0539-4e1c-afb2-44cb5e8ab48b.png">

**Comment by puneetkhanduri** [comment]
> Another improvement idea: give me an optional date input field, just entries older than this are dropped. (Or maybe also as range?)

Available in the latest master. Enjoy!
