### ISSUE TITLE
Not able to run the example

### ISSUE THREAD

**Issue by bcreaney** [opendiffy/diffy#74]
Hello. I'm following Quickstart guide to run the provided example, but once I start sending traffic I get the following errors:

`[otel.javaagent 2022-10-28 12:38:27:067 -0700] [ForkJoinPool.commonPool-worker-11] WARN io.opentelemetry.ApiUsageLogging - Instrument name "diffy.raw.json.result.headers.Date.PrimitiveDifference.differences" is invalid, returning noop instrument. Instrument names must consist of 63 or fewer characters including alphanumeric, _, ., -, and start with a letter. Returning noop instrument.`

and

`[otel.javaagent 2022-10-28 12:38:35:718 -0700] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317`

Nothing is displayed when I access http://localhost:8888/
The same happens with the advanced example using Docker. 

Any idea why this could be happening? 
Thank you

**Comment by puneetkhanduri** [comment]
Please try running the [example](/Quickstart.md) with the latest master. You should no longer see the errors. You should see something like this after sending traffic:
<img width="1428" alt="diffy-ui" src="https://user-images.githubusercontent.com/1631032/198785876-cc2342de-73e4-4e5a-ba51-e0f7ec8d2bf7.png">
That said, the errors you were seeing were benign and should not have caused any issues with the above example. If the issue still persists on your end please run the following commands and share the results you see:
`curl http://localhost:8888/api/1/endpoints?exclude_noise=false`

**Comment by bcreaney** [comment]
Thank you @puneetkhanduri. 

Once I hit http://localhost:8888/ using docker I'm not able to see any results, but I am able to see metrics/traces with Grafana/Jaeger/Prometheus. This issue only happens when running the example with docker.

**Comment by puneetkhanduri** [comment]
Can you share your docker logs along with the response of the above curl command.

**Comment by puneetkhanduri** [comment]
The curl command output indicates that Diffy is able to connect to primary, secondary, and candidate and process requests correctly.  Not sure why the UI is not able to show these results. Can you take a look at your browser's console and network logs to look for any exceptions there.

**Comment by bcreaney** [comment]
I'm not very familiar with frontend stuff but it seems to fail due to 
`Failed to load resource: the server responded with a status of 404 ()index.16be6bea.js`
however I can locate the file.

**Comment by puneetkhanduri** [comment]
This will require live screen sharing to debug. Please reach out to isotope@sn126.com to setup a time.
