### ISSUE TITLE
I have a question,  The result of diff is 9, but UI only show 5 diffs ,Can you help me with an answer? thanks 

### ISSUE THREAD

**Issue by liguohan** [opendiffy/diffy#79]
![image](https://user-images.githubusercontent.com/20010907/202456186-e748d333-f34d-40a5-bfbe-da3a39e61c75.png)

**Comment by puneetkhanduri** [comment]
This is an older version of Diffy. Please use the latest release.

**Comment by liguohan** [comment]
> This is an older version of Diffy. Please use the latest release.

Thank you for your reply，I used the latest version before，but I follow the documentation, when i run "java -jar -Dspring.config.location=diffy.yml diffy.jar" ,An error occurred,  I have submitted an issue 4 days ago
