### ISSUE TITLE
Why build failure in macos？

### ISSUE THREAD

**Issue by money8832** [opendiffy/diffy#80]
![image](https://user-images.githubusercontent.com/21093877/202637947-6426f712-a202-4fce-a5e8-3cf967991e86.png)

![image](https://user-images.githubusercontent.com/21093877/202638030-7a0453ad-5840-480a-a6fc-26cb10ab9240.png)

![image](https://user-images.githubusercontent.com/21093877/202638115-7fe09bee-07e5-43cf-8ae9-35a891bf26f6.png)

**Comment by puneetkhanduri** [comment]
This looks like an issue with your jdk version. Can you confirm what jdk version you have locally installed. Please upgrade your java version to at least 17.

Please feel free to comment on this issue if you are still facing problems.

**Comment by money8832** [comment]
![image](https://user-images.githubusercontent.com/21093877/202643926-d928b17b-6d7c-48a5-a724-fc1eb3726910.png)

**Comment by puneetkhanduri** [comment]
Please set your "Language level" to 17 or 18.

**Comment by money8832** [comment]
I set idea’s "Language level" to 17 or 18, but 👇🏻
![image](https://user-images.githubusercontent.com/21093877/202650677-c5f8d706-9c02-4a10-9a57-ca6b7fef2c9d.png)

**Comment by puneetkhanduri** [comment]
It's hard for me to troubleshoot your local environment issues remotely. May I suggest using the latest published jar or docker image if that can help you achieve your testing needs without having to build the code yourself.
