### ISSUE TITLE
Inverted primary/candidate results

### ISSUE THREAD

**Issue by joelmarty** [opendiffy/diffy#86]
I observed a strange behavior when trying out diffy: it seems that the results for "primary" and "candidate" are inverted in the detailed view of a difference ("Details" button in screenshot):

<img width="581" alt="image" src="https://user-images.githubusercontent.com/134835/231484794-2e19d523-d489-429e-a1e4-00f4a8e4061c.png">
 
I sent a request to my tested system and while the simple view correctly displayed the differences in "expected" (a.k.a primary) vs. "actual" (a.k.a candidate) columns, the response JSON payloads did not match that.

**Comment by puneetkhanduri** [comment]
@joelmarty : Can you please share steps for me to replicate and better understand this issue on my end.

**Comment by ilida** [comment]
I have the same problem

**Comment by ilida** [comment]
and I start diffy with docker,  in container where is the log directory.

**Comment by joelmarty** [comment]
Steps:
1. Make whatever request to diffy. Here I am making a request to the Twilio API (api.twilio.com)
2. Look at a difference, such as in the following screenshot:
<img width="807" alt="Screenshot 2023-04-18 at 15 09 00" src="https://user-images.githubusercontent.com/134835/232787551-279a7d8d-8a0c-4fec-93f0-2211a72de4e8.png">
3. Notice the ID ending in "f7" is in the "actual" column, which I understand as being the result to the candidate endpoint
4. Click on the "details" button
5. The id ending in "f7" is present in the JSON object for the "primary" request, where it would be expected to be in the "candidate" one.

**Comment by gomgomshrimp** [comment]
Same for me.
Additionally, when viewing the responses in `details`, the Primary and Candidate responses are swapped.
![스크린샷 2023-05-23 09 21 16](https://github.com/opendiffy/diffy/assets/12162614/0e393152-a258-4077-a7d2-dc9350f9173a)
