### ISSUE TITLE
error occurred in starting the diffy

### ISSUE THREAD

**Issue by LeonZXY** [opendiffy/diffy#9]
hi:

I have followed these steps in starting the diffy:
1. git clone https://github.com/opendiffy/diffy.git
2. cd diffy
3. ./example/run.sh start

And then the error happend. The log showed this : 

Build Diffy
Build primary, secondary, and candidate servers
Deploy Diffy
Error: Unable to access jarfile ./target/scala-2.12/diffy-server.jar
Deploy primary, secondary, and candidate servers
!!!failed to start!!!
!!!failed to start!!!
!!!failed to start!!!
Wait for server to deploy
Send some traffic to your Diffy instance
Your Diffy UI can be reached at http://localhost:8888

I could not find the diffy-server.jar in any directory of the diffy project
I send 'http://localhost:8888' in browser but it didn't work

where is the diffy-server.jar?
How can i deal with it??

**Comment by kshitij10496** [comment]
I'm facing the same error. Any pointers on how to fix it?

**Comment by puneetkhanduri** [comment]
@kshitij10496 : This should not be happening in the latest master. You can also run `./sbt assembly` directly to ensure that diffy-server.jar gets built.

**Comment by kshitij10496** [comment]
@puneetkhanduri  I got it working via Docker images! 🎉 

```sh
docker run --rm -d --name diffy-heroku \
  -ti -p 8880:8880 -p 8881:8881 -p 8888:8888 \
  diffy/diffy \
    -candidate=http-candidate.herokuapp.com:80 \
    -master.primary=http-primary.herokuapp.com:80 \
    -master.secondary=http-secondary.herokuapp.com:80 \
    -service.protocol=http \
    -serviceName="Heroku-Testing" \
    -proxy.port=:8880 \
    -admin.port=:8881 \
    -http.port=:8888 \
    -rootUrl=localhost:8888
```

I'm still facing issues with setting up diffy over HTTPS.
Can you suggest the changes that need to be made here?
I intend to use your suggestions as guidelines to use `diffy` in production. 😅

**Comment by kshitij10496** [comment]
@puneetkhanduri When running `./sbt assembly`, I get the following error message:

```sh
OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by CherryJlJ** [comment]
so how to solve it in the end?

**Comment by ronimachnes-vatbox** [comment]
I am facing the same issue with the jar when trying to run the example (and have the same problem with ./sbt assembly as specified in kshitij10496 comment). How can I solve this issue? Thank you in advance.
