### ISSUE TITLE
No prometheus metrics

### ISSUE THREAD

**Issue by fcamposdespegar** [opendiffy/diffy#90]
With last changes we lost prometheus metrics. Problem may be related with metric names.

**Comment by puneetkhanduri** [comment]
Users were running into [this issue](https://github.com/open-telemetry/opentelemetry-specification/issues/3422) with long metric names so we had to abbreviate and trim the names to avoid exceptions. The metrics are now being exported with abbreviated names as a stopgap solution which we don't like. Open to suggestions.

**Comment by suever** [comment]
@puneetkhanduri It seems as though the use of Prometheus labels could be beneficial to shorten the metric names but maintain legibility. Not only is the current approach difficult to read (and is not documented at all), it seems to combine values that should really be separated out (e.g. all GET requests get squashed into the same metric so you cannot filter based on path).

**Comment by puneetkhanduri** [comment]
@suever I can see the counter interface offers us the ability to provide tags in addition to metric names. Can you propose a naming structure until the long metric names issue is resolved. Here's what I currently have in mind:
```
name = <unabbreviated endpoint>.<abbreviated field>
tags = "type" , ("raw" | "noise")
```
Open to anything better you might have in mind.

**Comment by puneetkhanduri** [comment]
@fcamposdespegar @suever : Please share your feedback if any so we may address and close this issue.

**Comment by suever** [comment]
Sorry for the delay, I had to actually install an old version of opendiffy to determine what the metrics were supposed to represent based on the names before they were truncated.

I would propose something like the following where the cardinality will still be high, but the  number of metrics (and length of their names) is reasonable.

These examples may not be 100% accurate but provide an example of my thinking

```
diffy_requests_total{method="GET", path="/app"}
diffy_requests_differences_total{method="GET", path="/app", exclude=noise="true"}
diffy_requests_differences_total{method="GET", path="/app", exclude=noise="false"}
diffy_requests_differences_total{method="GET", path="/app", exclude_noise="true", key="headers"}
diffy_requests_differences_total{method="GET", path="/app", exclude_noise="true", key="body.field"}
diffy_requests_differences_total{method="GET", path="/app", exclude_noise="true", key="headers.accept-encoding"}

**Comment by puneetkhanduri** [comment]
Fixed in the latest release with the introduction of `endpoint` and `field` tags to corresponding metrics.
