### ISSUE TITLE
Unexpected comparison result format

### ISSUE THREAD

**Issue by aa3pankaj** [opendiffy/diffy#95]
Sample response:
`{
    "message": "Success",
    "response": {
        "id": 98758734857,
        "app": 12,
        "resource": {
            "id": 150,
            "app": null,
            "label": "Test label",
            "hfu": {
                "id": 898,
                "app": null,
                "createdDate": null,
                "lastModifiedDate": null,
                "name": "test_name",
                "uuid": null
            },
            "custom": false,
            "delhuf": false
        },
        "title": "Test title from candidate server",
        "abcd": "text",
        "related": [
            "ioi"
        ],
        "data": null,
        "functionLabel": "Test",
        "tcount": null,
        "type": "UYU",
        "gby": [],
        "meas": null,
        "audy": null,
        "stpe": null,
        "slimit": 0,
        "zin": null,
        "improvement": null,
        "isdaternfe": true,
        "meta": null,
        "inconfig": null,
        "metque": null,
        "fif": {
            "id": null,
            "requestResource": null,
            "resource": null,
            "updatable": false,
            "empty": true
        },
        "modified": false,
        "description": null,
        "initdat": null,
        "applyModifiedData": false,
        "sortConfiguration": null,
        "pastfore": null,
        "originalTitle": "Test original title",
        "uuid": "345345346",
        "cofn": null,
        "rol": null,
        "accessible": true,
        "hasDel": false,
        "witype": null,
        "empwi": false,
        "syd": null,
        "asgr": [],
        "ismod": false,
        "ughuygegg": false,
        "deleted": false,
        "newef": false,
        "efor": null
    },
    "path": null
}`

<img width="981" alt="Screenshot 2023-08-29 at 10 49 59 AM" src="https://github.com/opendiffy/diffy/assets/22378268/057843c6-96f7-4d4e-a7ca-87fb09d0b7b5">

Issue:
Unexpected "values" in the "Fields" section instead of actual key names from the response json.

Diffy release (latest): https://github.com/opendiffy/diffy/releases/tag/23.06.19.00

**Comment by puneetkhanduri** [comment]
This should be fixed with the latest release. Please redeploy and confirm.

**Comment by aa3pankaj** [comment]
Diffy is showing OrderingDifference for responses having arrays, e.g 
Primary server: 
[
    "xyz"
] 

Candidate: server
[
    "xyz"
] 

This is observed even if array is empty.

![image](https://github.com/opendiffy/diffy/assets/22378268/b6e3506f-9eeb-4060-9b7f-a43f07b55509)
